### ISSUE TITLE
SAIGE is not compatible with R 3.5.0 (and compile fails)

### ISSUE THREAD

**Issue by dequb** [weizhouUMICH/SAIGE#36]
Hi,
the latest SAIGE binary doesn't work with the latest R version (3.5.0), this error is displayed:

```
> library("SAIGE")
Error: package or namespace load failed for âSAIGEâ:
 package âSAIGEâ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

I tried compiling versions 0.26 and 0.29 from the sources but they both fail, at least on latest Ubuntu (Cosmic) or Debian testing, you can see the compile warnings and the error here: https://pastebin.com/61wR1sMq

Thanks!

**Comment by weizhouUMICH** [comment]
Hello, 
Sorry for my late reply. Now the version 0.29.3.2 works with R-3.5.1
https://github.com/weizhouUMICH/SAIGE/blob/master/SAIGE_0.29.3.2_R_x86_64-pc-linux-gnu.tar.gz

Thanks,
Wei

**Comment by buddyroo30** [comment]
Is R-3.5.1 a strict requirement, i.e. it only will work for that version of R (not with other more recent versions)? We need to use it along with many other R packages and need to use a newer version of R.

**Comment by weizhouUMICH** [comment]
Not necessarily.
Users will need to compile and install from the source code to make it with
other R versions, i.e. installation approach 2 and 3
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige

**Comment by buddyroo30** [comment]
Okay, thanks for the quick feedback. Unfortunately, I tried to build it with R-3.5.3 and it failed. I took your Dockerfile and first built it as-is (with R-3.5.1), and was successfully able to build the SAIGE Docker image. Then I modified your Dockerfile to replace R-3.5.1 with R-3.5.3 (and that is the only change I made), and that failed to build (the building of R succeeded, it just failed at the 'R CMD INSTALL SAIGE' step). This was the error output, FYI:

/usr/bin/ld: cannot find -lsavvy
/usr/bin/ld: cannot find -lhts
collect2: error: ld returned 1 exit status
/usr/local/lib/R/share/make/shlib.mk:6: recipe for target 'SAIGE.so' failed
make: *** [SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’
* removing ‘/usr/local/lib/R/library/SAIGE’
The command '/bin/sh -c R CMD INSTALL SAIGE' returned a non-zero code: 1

Do know what the problem is here and how it might be fixed? Thanks for your help.

**Comment by weizhouUMICH** [comment]
It seems that the savvy and hts libraries are not installed successfully.
They should be installed when you install SAIGE.
In the configure file,

rm -rf thirdParty/cget
cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix
thirdParty/cget -f thirdParty/requirements.txt

are used to install these two libraries.

Can you please check whether they are installed when run  'R CMD INSTALL
SAIGE' ?

Thanks,
Wei

**Comment by buddyroo30** [comment]
Actually, my bad, I don't know why it failed yesterday but I just tried again from scratch (using your Dockerfile except substituting R-3.5.3 for R-3.5.1) and it built successfully. So I'm going back to my own Dockerfile to install it (along with other stuff we need), but now I am getting this error about savvy:

* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘SAIGE’ ...
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz

Download failed with error 400 for: //github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e
.tar.gz
Failed to build package statgen/savvy
invalid lock file in /tmp/SAIGE/thirdParty/bgen
Setting top to                           : /tmp/SAIGE/thirdParty/bgen 
Setting out to                           : /tmp/SAIGE/thirdParty/bgen/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
zlib                                     : yes 
rt                                       : yes 
pthread                                  : yes 
dl                                       : yes 
'configure' finished successfully (0.301s)
Waf: Entering directory `/tmp/SAIGE/thirdParty/bgen/build'
...
...
...
Waf: Leaving directory `/tmp/SAIGE/thirdParty/bgen/build'
'build' finished successfully (32.118s)
** libs
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o SAIGE.so RcppExports.o test.o matrixMultiEigen.o SAIGE_fitGLMM_fast.o SAIGE_readDosage_bgen.o SAIGE_readDosage_plain.o SAIGE_readDosage_vcf.o SAIGE_GENE_readDosageMatrix_vcf.o ../thirdParty/bgen/build/src/MissingValue.cpp.2.o ../thirdParty/bgen/build/src/bgen.cpp.2.o ../thirdParty/bgen/build/src/zlib.cpp.2.o ../thirdParty/bgen/build/src/IndexQuery.cpp.2.o ../thirdParty/bgen/build/src/View.cpp.2.o ../thirdParty/bgen/build/db/libdb.a ../thirdParty/bgen/build/3rd_party/zstd-1.1.0/libzstd.a ../thirdParty/bgen/build/3rd_party/sqlite3/libsqlite3.a ../thirdParty/bgen/build/3rd_party/boost_1_55_0/libboost.a ../thirdParty/libsuperlu/usr/local/lib/libsuperlu.a -llapack -lblas -lgfortran -lm -lquadmath -L../bgen/3rd_party/boost_1_55_0/boost/iostreams -lboost_iostreams -L../thirdParty/cget/lib/ -lsavvy -lhts -L../thirdParty/libsuperlu/usr/local/lib/ -lsuperlu -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lsavvy
collect2: error: ld returned 1 exit status
make: *** [SAIGE.so] Error 1
/usr/share/R/share/make/shlib.mk:6: recipe for target 'SAIGE.so' failed
ERROR: compilation failed for package ‘SAIGE’
* removing ‘/usr/local/lib/R/site-library/SAIGE’
The command '/bin/sh -c cd /tmp/ && R CMD INSTALL SAIGE' returned a non-zero code: 1

So somehow it is failing to download/install savvy, do you know what the problem might be? FYI, I basically just copied everything from your Dockerfile to install SAIGE (except I didn't install R, because we already had version 3.5.3 of that installed).

**Comment by weizhouUMICH** [comment]
Maybe it has something to do with the internet?
Could you please try to put the
https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
in
a web browser to see if it is downloaded for you?

**Comment by buddyroo30** [comment]
Sorry, yes, forgot to mention that. I just ran the Docker container (that had failed at SAIGE) and was able to successfully wget that file when I manually did it. I also tried again to run 'R CMD INSTALL SAIGE' and in the error message for downloading savvy note that it truncates the https off:

# R CMD INSTALL SAIGE
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘SAIGE’ ...
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 400 for: //github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
Failed to build package statgen/savvy
Setting top to                           : /tmp/SAIGE/thirdParty/bgen 
Setting out to                           : /tmp/SAIGE/thirdParty/bgen/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
zlib                                     : yes 
rt                                       : yes 
pthread                                  : yes 
dl                                       : yes 
'configure' finished successfully (0.294s)

Any ideas? Any way I could just have the install process use the manual download of savvy that I did? Thanks for all your help with this.

**Comment by weizhouUMICH** [comment]
No worries.
You may try to download the SAIGE source code and run

cd /SAIGE/
rm -rf thirdParty/cget
cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix
thirdParty/cget -f thirdParty/requirements.txt

Then comment the two lines above in the configure file in the SAIGE folder

Then Run

R CMD INSTALL SAIGE

**Comment by buddyroo30** [comment]
Sorry for the delay trying this, had to work on some other stuff. Anyway, I tried what you suggested but I'm getting the same error (also showing the version of cget I'm using):

# cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix thirdParty/cget -f thirdParty/requirements.txt
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 400 for: //github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
Failed to build package statgen/savvy
root@907ef655336e:/SAIGE# cget --version
cget, version 0.1.7

Why is the "https:" being stripped off? Do I need to use a different version of cget? Or do you know what the problem might be? Thanks.

**Comment by weizhouUMICH** [comment]
Hi @buddyroo30, 

So sorry for taking so long to get back to you. I think the issue is because sometimes the url link to download dependencies is down. Now we have more stable ways to install the package, such as using a conda environment, please feel free to try. Thanks!

Wei
